import test from 'node:test';import assert from 'node:assert/strict';import {PAYLINES,PAYTABLE,FEATURE} from '../src/config/game.js';import {evaluateGrid,evaluateLine,GameEngine} from '../src/engine/game-engine.js';import {addCredits,load,save,reset,defaults,KEY} from '../src/storage/storage.js';
const blank=()=>Array.from({length:5},()=>['scatter','scatter','scatter']);
for(let n=0;n<9;n++)test(`payline ${n+1}`,()=>{const g=blank();PAYLINES[n].forEach((row,reel)=>g[reel][row]='rose');assert.ok(evaluateGrid(g).lines.some(x=>x.line===n));});
for(const count of [3,4,5])test(`${count} symbol win`,()=>{assert.equal(evaluateLine(Array.from({length:5},(_,i)=>i<count?'boat':'scatter')).count,count)});
for(let pos=0;pos<5;pos++)test(`wild substitution reel ${pos+1}`,()=>{const x=['rose','rose','rose','rose','rose'];x[pos]='wild';assert.equal(evaluateLine(x).symbol,'rose')});
test('multiple leading wilds choose highest valid payout',()=>assert.deepEqual(evaluateLine(['wild','wild','pelican','pelican','scatter']),{symbol:'pelican',count:4,payout:PAYTABLE.pelican[1]}));
test('five wilds',()=>assert.equal(evaluateLine(['wild','wild','wild','wild','wild']).payout,PAYTABLE.wild[2]));test('wild does not substitute scatter',()=>assert.equal(evaluateLine(['scatter','wild','scatter','scatter','scatter']),null));
test('three scatters trigger exactly eight',()=>{let e=new GameEngine({credits:1,rng:()=>.999});let g=blank();g[0][0]=g[1][1]=g[2][2]='scatter';assert.equal(evaluateGrid(g).trigger,true);e.feature={active:true,total:8,played:0,remaining:8,paused:true};assert.equal(e.feature.total,8)});test('two scatters do not trigger',()=>{let g=blank();g.flat().forEach(()=>{});g=Array.from({length:5},()=>['rose','boat','swan']);g[0][0]=g[1][1]='scatter';assert.equal(evaluateGrid(g).trigger,false)});
test('free games double payout',()=>{const g=Array.from({length:5},()=>['rose','scatter','scatter']);assert.equal(evaluateGrid(g,true).payout,evaluateGrid(g,false).payout*FEATURE.multiplier)});test('retrigger cap',()=>{const e=new GameEngine();e.feature={active:true,total:16,played:8,remaining:1};const old=e.spin.bind(e);e.spin=()=>{};const add=Math.min(5,18-e.feature.total);e.feature.total+=add;assert.equal(e.feature.total,18)});
test('paid deductions and free does not',()=>{const e=new GameEngine({credits:2,rng:()=>.5});e.spin();assert.ok(e.credits>=1);const before=e.credits;e.feature={active:true,total:8,played:0,remaining:8};e.spin({free:true});assert.ok(e.credits>=before)});
test('refill exact values',()=>{for(const n of [10,20,50])assert.equal(addCredits({credits:0},n).credits,n)});test('saved recovery and reset',()=>{const m=new Map(),s={getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};save({...defaults(),credits:20},s);assert.equal(load(s).credits,20);reset(s);assert.equal(load(s).credits,0)});
test('each payline is evaluated exactly once',()=>{const g=blank();PAYLINES[0].forEach((row,reel)=>g[reel][row]='rose');const result=evaluateGrid(g);assert.equal(result.lines.filter(line=>line.line===0).length,1);assert.equal(result.payout,result.lines.reduce((sum,line)=>sum+line.payout,0));});
test('all-wild award comes from configured paytable',()=>assert.equal(evaluateLine(['wild','wild','wild','wild','wild']).payout,PAYTABLE.wild[2]));
test('approved exact paytable',()=>assert.deepEqual(PAYTABLE,{rose:[1,2,5],boat:[2,4,8],swan:[2,5,10],lamp:[3,8,15],lighthouse:[5,12,25],pelican:[8,20,40],sunset:[12,30,60],steelworks:[20,50,100],wild:[0,0,200]}));
test('scatter anywhere in different rows triggers',()=>{const g=Array.from({length:5},()=>['rose','boat','swan']);g[0][0]=g[2][1]=g[4][2]='scatter';const r=evaluateGrid(g);assert.equal(r.trigger,true);assert.deepEqual(r.scatterPositions,[[0,0],[2,1],[4,2]]);});
test('scatter trigger is independent of paylines',()=>{const g=Array.from({length:5},()=>['rose','boat','swan']);g[0][2]=g[1][0]=g[4][1]='scatter';assert.equal(evaluateGrid(g).trigger,true);});
test('free win records base and multiplier exactly once',()=>{const g=Array.from({length:5},()=>['rose','scatter','scatter']);const r=evaluateGrid(g,true);assert.equal(r.multiplier,2);assert.equal(r.payout,r.basePayout*2);});
test('wild-assisted free win doubles exactly once',()=>{const g=Array.from({length:5},()=>['rose','scatter','scatter']);g[0][0]='wild';const r=evaluateGrid(g,true);assert.ok(r.lines.length);assert.equal(r.payout,r.basePayout*2);});
test('scatter has no cash award to double',()=>{const g=Array.from({length:5},()=>['boat','swan','lamp']);g[0][0]=g[2][1]=g[4][2]='scatter';const r=evaluateGrid(g,true);assert.equal(r.payout,r.basePayout*2);assert.ok(!r.lines.some(x=>x.symbol==='scatter'));});
test('nine paylines are the approved intuitive routes',()=>assert.deepEqual(PAYLINES,[
 [0,0,0,0,0],[1,1,1,1,1],[2,2,2,2,2],[0,1,2,1,0],[2,1,0,1,2],
 [1,0,0,0,1],[1,2,2,2,1],[0,1,1,1,0],[2,1,1,1,2]
]));
test('three matching symbols away from reel one do not win',()=>assert.equal(evaluateLine(['boat','rose','rose','rose','swan']),null));
