import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { defaults, load, save, KEY, SCHEMA_VERSION } from '../src/storage/storage.js';
import { GameEngine } from '../src/engine/game-engine.js';
import { goHome, HOME_PATH } from '../src/kiosk-navigation.js';
import { PAYTABLE } from '../src/config/game.js';

const memoryStorage = initial => { const values = new Map(initial ? [[KEY, initial]] : []); return { getItem: key => values.get(key) ?? null, setItem: (key,value) => values.set(key,value), removeItem: key => values.delete(key) }; };
const outcome = { grid: Array.from({length:5},()=>['rose','boat','swan']), lines: [], scatters: 0, trigger: false, payout: 4, free: false, credits: 13 };

test('normal state restoration includes settings',()=>{const storage=memoryStorage();const state=defaults();state.credits=22;state.sound=false;state.settings.reducedMotion=true;save(state,storage);assert.deepEqual(load(storage),state);});
test('restoration during free games preserves feature progress',()=>{const storage=memoryStorage();const state=defaults();state.credits=17;state.feature={active:true,total:13,played:5,remaining:8,paused:true};save(state,storage);assert.deepEqual(load(storage).feature,{...state.feature,win:0});});
test('reload after calculation restores completed outcome',()=>{const storage=memoryStorage();const state=defaults();state.credits=outcome.credits;state.pendingOutcome=outcome;save(state,storage);assert.deepEqual(load(storage).pendingOutcome,outcome);});
test('restored completed spin does not duplicate wager',()=>{const storage=memoryStorage();const engine=new GameEngine({credits:10,rng:()=>.5});const result=engine.spin();const state=defaults();state.credits=engine.credits;state.pendingOutcome=result;save(state,storage);const once=load(storage).credits;assert.equal(load(storage).credits,once);});
test('restored completed spin does not duplicate payout',()=>{const storage=memoryStorage();const state=defaults();state.credits=13;state.pendingOutcome=outcome;save(state,storage);const restored=load(storage);restored.pendingOutcome=null;save(restored,storage);assert.equal(load(storage).credits,13);});
test('corrupted local storage recovers safe defaults',()=>assert.deepEqual(load(memoryStorage('{not json')),defaults()));
test('unsupported storage version recovers safe defaults',()=>assert.deepEqual(load(memoryStorage(JSON.stringify({...defaults(),version:999}))),defaults()));
test('HOME saves before replacement navigation',()=>{const calls=[];goHome(()=>calls.push('save'),{replace:path=>calls.push(path)});assert.deepEqual(calls,['save',HOME_PATH]);});
test('launcher navigates to game with a relative local path',()=>{const html=fs.readFileSync('kiosk/index.html','utf8');assert.match(html,/href="games\/primbee-gold\/index\.html"/);assert.doesNotMatch(html,/href="(?:https?:)?\/\//);});
test('game returns to launcher with replacement navigation',()=>{assert.equal(HOME_PATH,'../../index.html');assert.match(fs.readFileSync('src/kiosk-navigation.js','utf8'),/\.replace\(HOME_PATH\)/);});
test('runtime sources contain no external URLs or window.open',()=>{const files=['index.html','styles.css','kiosk/index.html','kiosk/launcher.css',...fs.readdirSync('src',{recursive:true}).filter(name=>/\.(?:js|css|html)$/.test(name)).map(name=>`src/${name}`)];const text=files.map(file=>fs.readFileSync(file,'utf8')).join('\n');assert.doesNotMatch(text,/https?:\/\//i);assert.doesNotMatch(text,/window\.open\s*\(/);});
test('storage key is game-specific and schema is versioned',()=>{assert.equal(KEY,'primbee-gold:state');assert.equal(SCHEMA_VERSION,3);});
test('schema two migration preserves player and feature data',()=>{const old={version:2,credits:22,sound:false,settings:{volume:.4,reducedMotion:true,startingCredits:50},feature:{active:true,total:8,played:2,remaining:6,paused:true},lastWin:3,pendingOutcome:null};const storage=memoryStorage(JSON.stringify(old));const migrated=load(storage);assert.equal(migrated.version,3);assert.equal(migrated.credits,22);assert.equal(migrated.feature.remaining,6);assert.equal(migrated.settings.volume,.4);});
test('displayed result and win positions persist',()=>{const storage=memoryStorage(),state=defaults();state.credits=22;state.lastWin=3;state.displayedGrid=outcome.grid;state.displayedLines=[{line:1}];state.winningPositions=[[0,1],[1,1],[2,1]];state.status='TOTAL WIN 3';save(state,storage);assert.deepEqual(load(storage).displayedGrid,outcome.grid);assert.deepEqual(load(storage).winningPositions,state.winningPositions);assert.equal(load(storage).status,'TOTAL WIN 3');});
test('doubled feature presentation persists',()=>{const storage=memoryStorage(),state=defaults();state.lastWin=24;state.lastPresentation={basePayout:12,multiplier:2,payout:24,free:true};state.feature={active:true,total:8,played:2,remaining:6,paused:true,win:31};save(state,storage);assert.deepEqual(load(storage).lastPresentation,state.lastPresentation);assert.equal(load(storage).feature.win,31);});
test('symbol CSS gives every image a definite contained box',()=>{const css=fs.readFileSync('styles.css','utf8');assert.match(css,/\.cell img\{[^}]*width:100%;height:100%;[^}]*padding:3px;[^}]*object-fit:contain/);assert.match(css,/object-position:center/);assert.doesNotMatch(css,/--symbol-inset/);});
test('reel implementation has clipped full-cell passing symbols and predetermined landing',()=>{const app=fs.readFileSync('src/app.js','utf8'),css=fs.readFileSync('styles.css','utf8');assert.match(app,/const passing=12/);assert.match(app,/passingCell\.style\.height/);assert.match(app,/strip\.animate/);assert.match(app,/render\(result\.grid\)/);assert.match(css,/\.reel-window\{[^}]*overflow:hidden/);assert.ok(app.indexOf('engine.spin')<app.lastIndexOf('animateReels(result)'));});
test('spin transaction lock and presentation skip are explicit',()=>{const app=fs.readFileSync('src/app.js','utf8');assert.match(app,/if\(resolving\)return/);assert.match(app,/skipPresentation/);assert.match(app,/presentationToken\+\+/);});
test('reduced-motion direct landing is implemented',()=>{const app=fs.readFileSync('src/app.js','utf8');assert.match(app,/if\(reduced\(\)\)/);assert.match(app,/reduced-stop/);});
test('multiple line presentation is sequential',()=>{const app=fs.readFileSync('src/app.js','utf8');assert.match(app,/for\(const line of result\.lines\)/);assert.match(app,/await sleep\(reduced\(\)\?100:650\)/);});
test('count-up is accelerated and capped',()=>{const app=fs.readFileSync('src/app.js','utf8');assert.match(app,/Math\.min\(final>=100\?4000:2800,4000\)/);assert.match(app,/Math\.pow\(1-progress,2\)/);});
test('audio uses local recordings, respects off and synchronises coin ticks',()=>{const audio=fs.readFileSync('src/audio/audio.js','utf8');for(const file of ['slotPull.mp3','reelSpin.mp3','reelStop.mp3','slotWin.mp3','scatterHit.mp3','slotFeature.mp3','coinHandling.wav','winSmall.wav'])assert.match(audio,new RegExp(file.replace('.','\\.')));assert.match(audio,/if\(!this\.enabled\)return/);assert.match(audio,/sound\.volume=this\.volume/);assert.match(audio,/coinTimes\.push/);assert.doesNotMatch(audio,/Oscillator|createOscillator|tone\(/);});
test('win counter is in LAST WIN and paylines have an outlined SVG presentation',()=>{const html=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('src/app.js','utf8');assert.doesNotMatch(html,/id="winCount"/);assert.match(app,/const out=el\.lastWin/);assert.match(app,/createElementNS\(svg\.namespaceURI,'polyline'\)/);assert.match(app,/payline-outline/);assert.match(app,/drawPayline\(line\.positions\)/);});
test('production build includes every local recorded sound',()=>{const build=fs.readFileSync('scripts/build.mjs','utf8');assert.match(build,/'audio'/);});

test('refreshed artwork uses shared symbol sizing and the banner header',()=>{const html=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('src/app.js','utf8'),css=fs.readFileSync('styles.css','utf8');assert.match(app,/cell symbol-\$\{id\}/);assert.doesNotMatch(css,/--symbol-inset/);assert.match(html,/design-assets\/primbee-gold-banner\.png/);assert.doesNotMatch(html,/LAKE ILLAWARRA/);assert.match(css,/grid-template-rows:12% 9% minmax\(0,1fr\) 6% 15%/);assert.match(css,/\.brand img\{[^}]*width:100%;height:100%;[^}]*max-width:min\(520px,55vw\);[^}]*object-fit:contain;[^}]*object-position:center/);});
test('audio follows pull, progressive reel stops, visible wins, and actual scatters',()=>{const app=fs.readFileSync('src/app.js','utf8'),audio=fs.readFileSync('src/audio/audio.js','utf8');assert.ok(app.indexOf("audio.cue('spin')")<app.indexOf('await animateReels(result)'));assert.match(app,/audio\.reelLanded\(item\.reel\)/);assert.match(audio,/reelLanded\(reel\)/);assert.doesNotMatch(app,/cue\(free\?'free'/);assert.match(app,/scatterLandingDings\(result\.grid,item\.reel\)/);assert.match(app,/drawPayline\(line\.positions\);if\(line===result\.lines\[0\]\)audio\.cue/);assert.doesNotMatch(app,/audio\.completion/);});


test('RULES control and initially hidden modal are present',()=>{const html=fs.readFileSync('index.html','utf8');assert.match(html,/id="rulesButton"[^>]*>RULES</);assert.match(html,/id="rulesOverlay"[^>]*hidden/);assert.match(html,/id="closeRules"/);});
test('rules display derives the approved pay table and uses dashes for absent awards',()=>{assert.deepEqual(PAYTABLE,{rose:[1,2,3],boat:[1,2,3],swan:[1,2,4],lamp:[2,4,8],lighthouse:[2,6,12],pelican:[3,8,16],sunset:[1,5,12,25],steelworks:[2,8,20,40],wild:[0,0,100]});const app=fs.readFileSync('src/app.js','utf8');assert.match(app,/SYMBOLS\.filter\(\(\{id\}\)=>PAYTABLE\[id\]\)/);assert.match(app,/\[2,3,4,5\]\.map/);assert.match(app,/!awards\[count-firstCount\]\? '—'/);});
test('rules contain the approved concise instructions',()=>{const html=fs.readFileSync('index.html','utf8');for(const text of ['1 PLAY CREDIT PER SPIN','15 PAYLINES ARE ALWAYS ACTIVE','WINS START ON REEL 1 AND PAY LEFT TO RIGHT','SUNSET AND STEELWORKS CAN PAY FROM 2 SYMBOLS','OTHER REGULAR SYMBOLS REQUIRE 3 OR MORE','WILD SUBSTITUTES FOR REGULAR SYMBOLS','3 FREE SYMBOLS ANYWHERE = 8 FREE GAMES','FREE-GAME LINE WINS PAY ×2','WILD DOES NOT SUBSTITUTE FOR THE FREE SYMBOL'])assert.ok(html.includes(text),text);});
test('rules open and close without engine, credit, or persistence calls',()=>{const app=fs.readFileSync('src/app.js','utf8'),handlers=app.slice(app.indexOf('function closeRules()'),app.indexOf("el.spin.onclick"));assert.match(handlers,/if\(resolving\|\|presenting\)return/);assert.match(handlers,/rulesOverlay'\)\.hidden=false/);assert.match(handlers,/rulesOverlay'\)\.hidden=true/);assert.doesNotMatch(handlers,/engine|credits|persist|resolveSpin|location/);});
test('scatter landing dings count only final grid scatters, including two on one reel',async()=>{const app=fs.readFileSync('src/app.js','utf8'),source=app.match(/async function scatterLandingDings\(grid,reel\)\{.*?\}\}/s)[0],cues=[];const factory=new Function('audio','sleep',`${source};return scatterLandingDings`),ding=factory({cue:name=>cues.push(name)},()=>Promise.resolve());const grid=Array.from({length:5},()=>['rose','boat','swan']);for(const expected of [0,1,2,3]){cues.length=0;grid[0]=Array.from({length:3},(_,index)=>index<expected?'scatter':'rose');await ding(grid,0);assert.equal(cues.length,expected);}cues.length=0;grid[0]=['scatter','rose','scatter'];await ding(grid,0);assert.deepEqual(cues,['scatter','scatter']);});
test('scatter cues occur at final reel landing and not on passing-strip symbols',()=>{const app=fs.readFileSync('src/app.js','utf8');const passingStart=app.indexOf('const passing=12'),landing=app.indexOf('await scatterLandingDings(result.grid,item.reel)'),presentation=app.indexOf('async function present');assert.ok(passingStart<landing&&landing<presentation);assert.doesNotMatch(app.slice(passingStart,landing),/cue\('scatter'\)/);assert.match(app,/scatterLandingDings\(result\.grid,item\.reel\)/);assert.match(app,/scatterLandingDings\(result\.grid,reel\)/);});
test('trigger presentation adds no scatter cue and retains feature confirmation',()=>{const app=fs.readFileSync('src/app.js','utf8'),presentation=app.slice(app.indexOf('async function present'),app.indexOf('function skipPresentation'));assert.doesNotMatch(presentation,/cue\('scatter'\)/);assert.match(app,/if\(result\.trigger\)audio\.cue\('feature'\)/);});
