import fs from 'node:fs';
import path from 'node:path';
fs.rmSync('dist', { recursive: true, force: true });
fs.mkdirSync('dist/games/primbee-gold', { recursive: true });
fs.mkdirSync('dist/games/bush-bonanza', { recursive: true });
fs.cpSync('kiosk/index.html', 'dist/index.html');
fs.cpSync('kiosk/launcher.css', 'dist/launcher.css');
for (const item of ['index.html','styles.css','LICENSE','THIRD_PARTY_NOTICES.md','audio','design-assets','src']) fs.cpSync(item,path.join('dist/games/primbee-gold',item),{recursive:true});
for (const item of ['index.html','styles.css','bush.css','LICENSE','THIRD_PARTY_NOTICES.md','audio','design-assets','src']) fs.cpSync(path.join('games/bush-bonanza',item),path.join('dist/games/bush-bonanza',item),{recursive:true});
console.log('Built Club Mick with Primbee Gold and Bush Bonanza');
